### ISSUE TITLE
Looky Looker

### ISSUE THREAD

**Issue by javierarce** [notjuliet/awesome-bluesky#38]
I'm not sure if this qualifies as awesome, but I created a simple page to find out which Bluesky lists somebody is on: https://bsky.javier.computer

**Comment by notjuliet** [comment]
i mean tbh i think not having to use clearsky.app slow ass web view to see what's arguably the only good feature it has is a worthwile addition

**Comment by javierarce** [comment]
Thanks, Juliet!

**Comment by notjuliet** [comment]
might have to fix pagination tho
doesnt seem to go beyond 100 lists

**Comment by javierarce** [comment]
Oh, true! 😅

**Comment by javierarce** [comment]
Ok, I added a button to load more lists. Eg: https://bsky.javier.computer/?user=craigmod.com
